#!/usr/bin/perl -w
# $Id: calendar,v 1.3 2013/07/14 22:54:04 tom Exp $

#
# Purpose:
#	To demonstrate the Perl5 Cdk Calendar Widget

use strict;

#
# Initialize Cdk.
#
use Cdk;
Cdk::init();

# Create the celendar object.
my $calendar = new Cdk::Calendar();

# Activate the object.
my $ret = $calendar->activate();

# Exit Cdk.
Cdk::end();
