#!/usr/bin/perl -w
# $Id: calendar,v 1.2 2002/07/27 20:11:17 tom Exp $

#
# Purpose:
#	To demonstrate the Perl5 Cdk Calendar Widget

#
# Initialize Cdk.
#
use Cdk;
Cdk::init();

# Create the celendar object.
my $calendar = new Cdk::Calendar ();

# Activate the object.
my $ret = $calendar->activate();

# Exit Cdk.
Cdk::end();
