#!/usr/bin/perl -w
# $Id: entry,v 1.3 2013/07/14 22:53:31 tom Exp $

#
# Purpose:
#	To demonstrate the Perl5 Cdk Entry Widget.

use strict;

#
# Load in the Cdk Extension.
#
use Cdk;
Cdk::init();

# Create a new entry object.
my $entry = new Cdk::Entry(
    'Label' => "Type Anything: ",
    'Width' => 20,
    'Min'   => 0,
    'Max'   => 256
);

# Activate the object.
my $info = $entry->activate();

# Check the results.
if ( !defined $info ) {
    popupLabel( ["<C>You hit escape, nothing returned."] );
}
else {
    popupLabel( ["<C>You typed in ($info)"] );
}

# Exit Cdk.
Cdk::end();
