#!/usr/bin/perl -w
# $Id: label,v 1.3 2013/07/14 22:49:54 tom Exp $

#
# Purpose:
#	To demonstrate the Perl5 Cdk Label Widget.

use strict;

#
# Initialize Cdk.
#
use Cdk;
Cdk::init();

# Set up the label rows.
my @mesg = (
    "<C>This is a test of the Perl Cdk extension.",
    "", "",
    "<L></22>Written by...",
    "<C></5/R>Mike Glover"
);

# Create the label object.
my $title = new Cdk::Label( 'Message' => \@mesg );

# Draw the label.
$title->set( 'BoxAttribute' => "</B>" );
$title->draw();
$title->wait();

# Exit Cdk.
Cdk::end();
