#!/usr/bin/perl -w
# $Id: marquee,v 1.3 2013/07/14 21:28:19 tom Exp $

#
# Purpose:
#	To demonstrate the Perl5 Cdk Marquee Widget.

use strict;

#
# Initialize Cdk.
#
use Cdk;
Cdk::init();

# Create the message to scroll.
my $message = "</5>Hello there</K>!!!<!K> How are you today?<!5> ";

# Create the marquee object.
my $marquee = new Cdk::Marquee( 'Width' => 20 );

# Activate the marquee object.
$marquee->activate(
    'Message' => $message,
    'Delay'   => 3,
    'Repeat'  => 3
);

# Exit Cdk.
Cdk::end();
