#!/usr/bin/perl -w
# $Id: mentry,v 1.3 2013/07/14 22:48:20 tom Exp $

#
# Purpose:
#	To demonstrate the Perl5 Cdk Mentry Widget

use strict;

#
# Load in the Cdk Extension.
#
use Cdk;

#
# Initialize Cdk.
#
Cdk::init();

# Create the multi-line entry object.
my $mentry = new Cdk::Mentry(
    'Label' => "</5>Filename: ",
    'Width' => 20,
    'Prows' => 5,
    'Lrows' => 10
);

# Activate the object.
my $filename = $mentry->activate();

# Check the results.
if ( !defined $filename ) {
    popupLabel( ["<C>Escape hit. No information returned."] );
}
else {
    popupLabel( [ "<C>You typed in", "<C>$filename" ] );
}

# Shut down Cdk.
Cdk::end();
